### PR TITLE
Suggest users to use Thamos CLI to create requirements file

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/kebechet/issues/945

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by codificat** [comment]
/approve
thanks!

**Comment by codificat** [comment]
/hold
one sec, just tried this verbatim in the aicoe-ci-pulp-upload-example repo and it did not generate a Pipfile

**Comment by codificat** [comment]
> one sec, just tried this verbatim in the aicoe-ci-pulp-upload-example repo and it did not generate a Pipfile

@fridex can we (should we?) expand the change to explain the requirements for this to work?
I was thinking "point to the `thamos discover` CLI documentation", but I could not find that

**Review by harshad16 — COMMENTED** [review]
lgtm :+1:

**Comment by fridex** [comment]
> > one sec, just tried this verbatim in the aicoe-ci-pulp-upload-example repo and it did not generate a Pipfile
> 
> @fridex can we (should we?) expand the change to explain the requirements for this to work? I was thinking "point to the `thamos discover` CLI documentation", but I could not find that

What error are you seeing? We had a bug when the response from the server is not properly serialized:

```
Invalid value for `_import`, must not be `None`
```

That should be addressed in the next release.

**Comment by codificat** [comment]
> What error are you seeing?

I don't see an error per se, only that a Pipfile is not created when just calling `thamos discover`:

```
pep@uio aicoe-ci-pulp-upload-example (master) $ ls
aicoe  CHANGELOG.md  LICENSE  OWNERS  README.rst  requirements.txt  setup.py
pep@uio aicoe-ci-pulp-upload-example (master) $ thamos discover --src-path ./
2022-01-12 15:03:25,410 [40951] INFO     thamos.lib: Performing static analysis of sources to gather library usage
2022-01-12 15:03:25,415 [40951] WARNING  thamos.config: TLS verification turned off, its highly recommended to use a secured connection, see configuration file for configuration options
2022-01-12 15:03:25,812 [40951] WARNING  thamos.lib: No packages identified for import name __builtins__: (404)
Reason: NOT FOUND
HTTP response headers: HTTPHeaderDict({'server': 'gunicorn', 'date': 'Wed, 12 Jan 2022 14:03:26 GMT', 'content-type': 'application/json', 'content-length': '137', 'x-thoth-version': '0.27.2', 'x-user-api-service-version': '0.27.2+messaging.0.15.0.storages.0.58.0.common.0.32.0.python.0.16.5', 'access-control-allow-origin': '*', 'set-cookie': '99770cb82864be05282857f803e02327=c7700951228e7856b0531f56d33880a8; path=/; HttpOnly; Secure; SameSite=None', 'cache-control': 'private'})
HTTP response body: b'{\n  "error": "No package name records for package \'__builtins__\' in database",\n  "parameters": {\n    "import_name": "__builtins__"\n  }\n}\n'

2022-01-12 15:03:26,120 [40951] WARNING  thamos.lib: No packages identified for import name os: (404)
Reason: NOT FOUND
HTTP response headers: HTTPHeaderDict({'server': 'gunicorn', 'date': 'Wed, 12 Jan 2022 14:03:26 GMT', 'content-type': 'application/json', 'content-length': '117', 'x-thoth-version': '0.27.2', 'x-user-api-service-version': '0.27.2+messaging.0.15.0.storages.0.58.0.common.0.32.0.python.0.16.5', 'access-control-allow-origin': '*', 'set-cookie': '99770cb82864be05282857f803e02327=c7700951228e7856b0531f56d33880a8; path=/; HttpOnly; Secure; SameSite=None', 'cache-control': 'private'})
HTTP response body: b'{\n  "error": "No package name records for package \'os\' in database",\n  "parameters": {\n    "import_name": "os"\n  }\n}\n'

2022-01-12 15:03:26,472 [40951] WARNING  thamos.lib: No packages identified for import name setuptools: Invalid value for `_import`, must not be `None`
2022-01-12 15:03:26,842 [40951] WARNING  thamos.lib: No packages identified for import name logging: (404)
Reason: NOT FOUND
HTTP response headers: HTTPHeaderDict({'server': 'gunicorn', 'date': 'Wed, 12 Jan 2022 14:03:27 GMT', 'content-type': 'application/json', 'content-length': '127', 'x-thoth-version': '0.27.2', 'x-user-api-service-version': '0.27.2+messaging.0.15.0.storages.0.58.0.common.0.32.0.python.0.16.5', 'access-control-allow-origin': '*', 'set-cookie': '99770cb82864be05282857f803e02327=c7700951228e7856b0531f56d33880a8; path=/; HttpOnly; Secure; SameSite=None', 'cache-control': 'private'})
HTTP response body: b'{\n  "error": "No package name records for package \'logging\' in database",\n  "parameters": {\n    "import_name": "logging"\n  }\n}\n'

2022-01-12 15:03:27,154 [40951] WARNING  thamos.lib: No packages identified for import name aicoe: (404)
Reason: NOT FOUND
HTTP response headers: HTTPHeaderDict({'server': 'gunicorn', 'date': 'Wed, 12 Jan 2022 14:03:27 GMT', 'content-type': 'application/json', 'content-length': '123', 'x-thoth-version': '0.27.2', 'x-user-api-service-version': '0.27.2+messaging.0.15.0.storages.0.58.0.common.0.32.0.python.0.16.5', 'access-control-allow-origin': '*', 'set-cookie': '99770cb82864be05282857f803e02327=c7700951228e7856b0531f56d33880a8; path=/; HttpOnly; Secure; SameSite=None', 'cache-control': 'private'})
HTTP response body: b'{\n  "error": "No package name records for package \'aicoe\' in database",\n  "parameters": {\n    "import_name": "aicoe"\n  }\n}\n'

2022-01-12 15:03:27,495 [40951] WARNING  thamos.lib: No packages identified for import name click: Invalid value for `_import`, must not be `None`
pep@uio aicoe-ci-pulp-upload-example (master) $ ls Pipfile
ls: cannot access 'Pipfile': No such file or directory
```

What I meant is that I believe that the proposed change is good, but it probably needs some additional pointers for end users to know how to handle it.

**Comment by fridex** [comment]
It is a schema issue. A new user-api and thamos will soon address this issue:

```
2022-01-12 15:03:27,495 [40951] WARNING  thamos.lib: No packages identified for import name click: Invalid value for `_import`, must not be `None`
```

The problem is that import is a keyword in Python which caused troubles in thamos.

**Comment by codificat** [comment]
> It is a schema issue. A new user-api and thamos will soon address this issue:

Should we hold until that's available then?

I'm mostly concerned about user experience here. Beyond that specific issue, I believe it would be good to provide a pointer to docs/further help, in case something (else) goes wrong.

**Comment by fridex** [comment]
> > It is a schema issue. A new user-api and thamos will soon address this issue:
> 
> Should we hold until that's available then?

I don't think this is blocking now - we will soon propagate the update to fix it.

> I'm mostly concerned about user experience here. Beyond that specific issue, I believe it would be good to provide a pointer to docs/further help, in case something (else) goes wrong.

Yes, sorry - here is a patch fix: https://github.com/thoth-station/user-api/pull/1591 Thamos hasn't been released yet with the schema change.

**Comment by codificat** [comment]
Fair enough :+1: thanks.
/unhold

**Pull request merged**
