### PR TITLE
Added error message for duplicate packages

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies
Fixes - #574 
Added an error message issue and also close it automatically when fixed, tested on adviser fork.

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
@fridex I am not sure if we want this any-more?

**Comment by fridex** [comment]
> @fridex I am not sure if we want this any-more? Its a corner case in which the user repeats the package.

I think duplicate entries are not possible in Pipfile (TOML):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "<0.6"
flask = "*"

[dev-packages]

[requires]
python_version = "3.8"
```

raises:

```python
toml.decoder.TomlDecodeError: Duplicate keys! (line 15 column 1 char 228)
```

If that's for dev-packages and packages, I think this could be handled transparently by Pipenv. So +1 on closing this. We should switch to Thoth based update anyway.

**Comment by saisankargochhayat** [comment]
Thanks for confirming. :+1:

**Pull request closed without merging**
