### PR TITLE
please help me with myreponame

### PR DESCRIPTION
**Pull request by durandom**

### CODE REVIEW

**Comment by goern** [comment]
I guess he wants this repo to be managed

**Comment by fridex** [comment]
> I guess he wants this repo to be managed

@durandom then, please move this entry to config/thoth.yaml

BTW we should consider deploying another kebechet instance that would use entries from a new config file (e.g. separated kebechet for aicoe repos). The current one seems to be overwhelmed.

**Comment by durandom** [comment]
I'm following the instructions at https://thoth-station.ninja/kebechet/how-to-integrate/

what should I do now?

**Comment by fridex** [comment]
> I'm following the instructions at https://thoth-station.ninja/kebechet/how-to-integrate/
> 
> what should I do now?

Just move the entry you have created in `config/durandom_64fbc27e213f5a61c975ab29df94536b88f03270.yaml` to `config/thoth.yaml` (append it there).

**Comment by durandom** [comment]
@fridex like this?

**Pull request merged**
