### PR TITLE
Remove thoth-station/package-analyzer

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by goern** [comment]
/assign @fridex 

please have a look at the pre-commit errors, thx!

**Comment by fridex** [comment]
> please have a look at the pre-commit errors, thx!

Yes, I looked at them. They do not seem to be relevant to this PR. Can be fixed in another PR addressing the pre-commit complaints.

**Comment by goern** [comment]
@fridex ping

**Comment by fridex** [comment]
Errors are not related to this PR. Will rebase and merge.

**Pull request merged**
