### PR TITLE
port to python 38

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
https://github.com/thoth-station/kebechet/issues/295

**Comment by saisankargochhayat** [comment]
Let's wait on this port for a while? I want to test if the importlib issue is fixed in the latest release

**Comment by bissenbay** [comment]
> portlib issue is fixed in the la

sure @saisankargochhayat , please let me know once you resolve it

**Comment by harshad16** [comment]
The deploy has failed because the build cant be done, that can be also seen in the statues, the build-check has failed, so the container image cant be build.

**Comment by harshad16** [comment]
have a look at the pr-buid-release-run > build 
https://tekton-dashboard-openshift-pipelines.apps.ocp4.prod.psi.redhat.com/#/namespaces/aicoe-infra-prod/pipelineruns/aicoe-pipelinerun-8jmb5

**Comment by saisankargochhayat** [comment]
```
(kebechet) [sai@sai-pc kebechet]$ pytest
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/sai/Downloads/thoth-station/kebechet
plugins: cov-2.10.1, timeout-1.4.2
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
__________ ERROR collecting kebechet/managers/version/version_test.py __________
ImportError while importing test module '/home/sai/Downloads/thoth-station/kebechet/kebechet/managers/version/version_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
kebechet/__init__.py:4: in <module>
    from .managers import InfoManager  # noqa F401
kebechet/managers/__init__.py:7: in <module>
    from .thoth_advise import ThothAdviseManager
kebechet/managers/thoth_advise/__init__.py:20: in <module>
    from .thoth_advise import ThothAdviseManager  # noqa F401
kebechet/managers/thoth_advise/thoth_advise.py:25: in <module>
    from thamos import lib
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/thamos/lib.py:40: in <module>
    from thoth.python import Project
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/thoth/python/__init__.py:29: in <module>
    from .aiosource import AIOSource, AsyncIterablePackages, AsyncIterableVersions, AsyncIterableArtifacts
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/thoth/python/aiosource.py:29: in <module>
    import aiohttp
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib64/python3.8/site-packages/aiohttp/__init__.py:6: in <module>
    from .client import (
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib64/python3.8/site-packages/aiohttp/client.py:35: in <module>
    from . import hdrs, http, payload
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib64/python3.8/site-packages/aiohttp/http.py:7: in <module>
    from .http_parser import (
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib64/python3.8/site-packages/aiohttp/http_parser.py:15: in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib64/python3.8/site-packages/aiohttp/helpers.py:48: in <module>
    from typing_extensions import Protocol
E   ModuleNotFoundError: No module named 'typing_extensions'
=============================== warnings summary ===============================
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/pip/_vendor/toml/decoder.py:47
  /home/sai/.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/pip/_vendor/toml/decoder.py:47: DeprecationWarning: invalid escape sequence \.
    TIME_RE = re.compile("([0-9]{2}):([0-9]{2}):([0-9]{2})(\.([0-9]{3,6}))?")

../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/attrdict/mapping.py:4
  /home/sai/.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/attrdict/mapping.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Mapping

../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/attrdict/mixins.py:5
../../../.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/attrdict/mixins.py:5
  /home/sai/.local/share/virtualenvs/kebechet-mrr_QWn5/lib/python3.8/site-packages/attrdict/mixins.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Mapping, MutableMapping, Sequence

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
ERROR kebechet/managers/version/version_test.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 4 warnings, 1 error in 2.01s =========================
```
I feel like this is what preventing from the build from passing.

**Comment by harshad16** [comment]
its the fasttext installation is causing the failure .

**Comment by saisankargochhayat** [comment]
> its the fasttext installation is causing the failure .

Is it an issue with Python 3.8? It seems to be passing on other PR's

**Comment by harshad16** [comment]
> Is it an issue with Python 3.8? It seems to be passing on other PR's

yes related to python3.8. 
i m myself checking, can really pin it down to a specific reason. 
if i find something i will provide more insights :smile:

**Comment by saisankargochhayat** [comment]
> > Is it an issue with Python 3.8? It seems to be passing on other PR's
> 
> yes related to python3.8.
> i m myself checking, cann't really pin it down to a specific reason.
> if i find something i will provide more insights

Thanks, I will try locking again.

**Pull request merged**
