### PR TITLE
Copying pr 621

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies

Test PR

### CODE REVIEW

**Comment by harshad16** [comment]
statues check happens on commits. so the results would be pretty same.

**Comment by saisankargochhayat** [comment]
https://tekton-dashboard-openshift-pipelines.apps.ocp4.prod.psi.redhat.com/#/namespaces/aicoe-infra-prod/pipelineruns/aicoe-pipelinerun-tw2pd
@harshad16 here it seems the build has passed.

**Comment by harshad16** [comment]
It hasnt.
```
[pipenv.exceptions.InstallError]:                      from /home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/pybind11/include/pybind11/pybind11.h:45,
[pipenv.exceptions.InstallError]:                      from /home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:12,
[pipenv.exceptions.InstallError]:                      from python/fasttext_module/fasttext/pybind/fasttext_pybind.cc:13:
[pipenv.exceptions.InstallError]:     /home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/pybind11/include/pybind11/detail/common.h:122:10: fatal error: Python.h: No such file or directory
[pipenv.exceptions.InstallError]:      #include <Python.h>
[pipenv.exceptions.InstallError]:               ^~~~~~~~~~
[pipenv.exceptions.InstallError]:     compilation terminated.
[pipenv.exceptions.InstallError]:     error: command '\''gcc'\'' failed with exit status 1
[pipenv.exceptions.InstallError]:     ----------------------------------------
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: /home/user/.local/share/virtualenvs/user-5PivF_Od/bin/python -u -c '\''import sys, setuptools, tokenize; sys.argv[0] = '\''"'\''"'\''/tmp/pip-install-rj88hrdu/fasttext/setup.py'\''"'\''"'\''; __file__='\''"'\''"'\''/tmp/pip-install-rj88hrdu/fasttext/setup.py'\''"'\''"'\'';f=getattr(tokenize, '\''"'\''"'\''open'\''"'\''"'\'', open)(__file__);code=f.read().replace('\''"'\''"'\''\r\n'\''"'\''"'\'', '\''"'\''"'\''\n'\''"'\''"'\'');f.close();exec(compile(code, __file__, '\''"'\''"'\''exec'\''"'\''"'\''))'\'' install --record /tmp/pip-record-m54dt7fa/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.local/share/virtualenvs/user-5PivF_Od/include/site/python3.8/fasttext Check the logs for full command output.
ERROR: Couldn'\''t install package: fasttext
```
green color doesn't determine if the check has passed 
if the build-check is failed the detailed would be shown in the build-check > build

**Comment by saisankargochhayat** [comment]
> It hasnt.
> 
> ```
> [pipenv.exceptions.InstallError]:                      from /home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/pybind11/include/pybind11/pybind11.h:45,
> [pipenv.exceptions.InstallError]:                      from /home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:12,
> [pipenv.exceptions.InstallError]:                      from python/fasttext_module/fasttext/pybind/fasttext_pybind.cc:13:
> [pipenv.exceptions.InstallError]:     /home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/pybind11/include/pybind11/detail/common.h:122:10: fatal error: Python.h: No such file or directory
> [pipenv.exceptions.InstallError]:      #include <Python.h>
> [pipenv.exceptions.InstallError]:               ^~~~~~~~~~
> [pipenv.exceptions.InstallError]:     compilation terminated.
> [pipenv.exceptions.InstallError]:     error: command '\''gcc'\'' failed with exit status 1
> [pipenv.exceptions.InstallError]:     ----------------------------------------
> [pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: /home/user/.local/share/virtualenvs/user-5PivF_Od/bin/python -u -c '\''import sys, setuptools, tokenize; sys.argv[0] = '\''"'\''"'\''/tmp/pip-install-rj88hrdu/fasttext/setup.py'\''"'\''"'\''; __file__='\''"'\''"'\''/tmp/pip-install-rj88hrdu/fasttext/setup.py'\''"'\''"'\'';f=getattr(tokenize, '\''"'\''"'\''open'\''"'\''"'\'', open)(__file__);code=f.read().replace('\''"'\''"'\''\r\n'\''"'\''"'\'', '\''"'\''"'\''\n'\''"'\''"'\'');f.close();exec(compile(code, __file__, '\''"'\''"'\''exec'\''"'\''"'\''))'\'' install --record /tmp/pip-record-m54dt7fa/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.local/share/virtualenvs/user-5PivF_Od/include/site/python3.8/fasttext Check the logs for full command output.
> ERROR: Couldn'\''t install package: fasttext
> ```
> 
> green color in pipeline task doesn't determine if the check has passed
> if the build-check is failed the detailed would be shown in the build-check > build

Could it be a issue with the version of Pipenv the pipeline is using? Is it pipenv==2020.11.15

**Comment by fridex** [comment]
> Could it be a issue with the version of Pipenv the pipeline is using? Is it pipenv==2020.11.15

fastext has just source distribution published https://pypi.org/project/fasttext/0.9.2/#files (if 0.9.2 is used) which causes the build process to start for building the native extensions. This build process requires Python 3.8 headers that are not present in the kebechet environment (something like python38-devel).

**Pull request closed without merging**
