### PR TITLE
Remove unnecessary quotes

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
See for example https://github.com/thoth-station/tensorflow-symbols/issues/1#issue-740694147

**Review by harshad16 — APPROVED** [review]
thanks

**Review by saisankargochhayat — APPROVED** [review]
Thanks :+1:

**Comment by saisankargochhayat** [comment]
Might need a manual merge

**Pull request merged**
