### PR TITLE
Update old PRs on top of the current master

### PR DESCRIPTION
**Pull request by fridex**
Fixes: #15

### CODE REVIEW

**Comment by harshad16** [comment]
\lgtm
\approve
\assign @goern

**Comment by goern** [comment]
nice @harshad16 you have been using windows for way toooo loooong.. \ | / - \ | / - 

/assign

**Comment by goern** [comment]
is #12 related? @fridex @harshad16

**Comment by fridex** [comment]
Do not merge please. I'm unable to build the kebechet image - I have some issues on my machine so this is not tested from my side.

**Comment by goern** [comment]
you can always `/approve cancel` or `/lgtm cancel`

**Comment by fridex** [comment]
Heh, merged at the right time... We should handle PRs correctly now, see README notes.

**Pull request merged**
