### PR TITLE
Add branch for if thoth configuration blocks advise submission

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

https://github.com/thoth-station/support/issues/93

I also added a couple changes as to how errors are handled. They will only exist as comments to the issue opened for advise. If errors are present the issue will stay open until the user closes it.

### CODE REVIEW

**Comment by goern** [comment]
any updates?

**Review by fridex — APPROVED** [review]
Looks really good 👍🏻 Thanks!

**Pull request merged**
