### PR TITLE
[WIP] Replaced update manager with thoth-advise

### PR DESCRIPTION
**Pull request by saisankargochhayat**
Depends on - https://github.com/thoth-station/srcops-testing/pull/229
If the advise manager successfully updates srcops-testing

### CODE REVIEW

**Comment by goern** [comment]
@KPostOffice whats the state of this?

**Comment by pacospace** [comment]
> @KPostOffice whats the state of this?

We need to test it I think, but in stage environment (old cluster), we need all images available in the namespace where the workflow needs to run (adviser, workflow-helpers, unresolved-packages-handler and graph-sync) to use new adviser template for the workflow: https://github.com/thoth-station/adviser/blob/master/openshift/adviser-template.yaml

**Comment by goern** [comment]
@KPostOffice this is replaced by some of your work, right?

**Comment by goern** [comment]
/priority backlog

@KPostOffice ping

**Comment by goern** [comment]
/remove-lifecycle rotten.

ping @KPostOffice aren't you actively working on this one?!

**Comment by goern** [comment]
@KPostOffice ping

**Pull request closed without merging**
