### PR TITLE
close duplicate release issues when manager is run

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/support/issues/192

## This introduces a breaking change

- [ ] Yes
- [ ] No

## This Pull Request implements

After writing a version release PR we close any other version release triggers.

### CODE REVIEW

**Comment by goern** [comment]
is this good to be merged?

**Comment by KPostOffice** [comment]
@goern Should be now

**Review by fridex — COMMENTED** [review]
looks good to me! thanks! 💯 👍🏻 

/approve

**Pull request merged**
