### PR TITLE
Fix if automatic relocking PR exists

### PR DESCRIPTION
**Pull request by saisankargochhayat**
Reverts thoth-station/kebechet#400 and merges #381 
Sorry about the wrong merge.

### CODE REVIEW

**Comment by goern** [comment]
/assign @saisankargochhayat 

is this still valid?

**Comment by saisankargochhayat** [comment]
@fridex It seems like a corner case, I am not sure do we want it or not?

**Comment by fridex** [comment]
> @fridex It seems like a corner case, I am not sure do we want it or not?

I think it might be valuable. WDYT?

**Comment by saisankargochhayat** [comment]
> > @fridex It seems like a corner case, I am not sure do we want it or not?
> 
> I think it might be valuable. WDYT?

Let me rebase it, we can merge it maybe :+1:

**Comment by saisankargochhayat** [comment]
Moved to #486

**Pull request closed without merging**
