### PR TITLE
update version manager to act on PR merge with labels

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

extend Kebechet version manager to act on certain PRs as well

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Contains major refactor of Kebechet version manager. Needs testing before merging

### CODE REVIEW

**Comment by KPostOffice** [comment]
https://github.com/KPostOffice/khebhut_test/pull/23

**Comment by goern** [comment]
bouce

**Review by fridex — APPROVED** [review]
nice! looks good to me 👍🏻

**Pull request merged**
