### PR TITLE
Uninstall unused libraries

### PR DESCRIPTION
**Pull request by tlegen-k**
## Related Issues and Dependencies
Issue #727 
…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Start creating new kebechet manager to uninstall unused packages from Pipfile.
Work is still in progress.

### CODE REVIEW

**Comment by tlegen-k** [comment]
Hi @KPostOffice. 
Do I understand it correctly that closest manager in terms of functionality to the goals - Kebechet Pipfile Requirements Manager?

**Comment by tlegen-k** [comment]
@KPostOffice would you be able to point at how to check whether library is used?

**Comment by KPostOffice** [comment]
@tlegen-k See [invectio](https://github.com/thoth-station/invectio), it gathers Python symbol usage. I think this is your best option. Let me know if you have any questions.

**Comment by pacospace** [comment]
> @tlegen-k See [invectio](https://github.com/thoth-station/invectio), it gathers Python symbol usage. I think this is your best option. Let me know if you have any questions.

This will actually use the new endpoint in user API, using https://github.com/thoth-station/storages/pull/2410?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDIyMjEwNzA2ODM6Mjc0OTg2Nzk%3D#pullrequestreview-729376815, combined with invectio's output. Wdyt?

**Comment by goern** [comment]
is this a draft PR or WIP?

**Pull request closed without merging**
