### PR TITLE
use thamos.lib.write_files

### PR DESCRIPTION
**Pull request by KPostOffice**
Use write_files to write requirements files to directory

### CODE REVIEW

**Comment by harshad16** [comment]
@KPostOffice rebease is needed in this one.

**Comment by goern** [comment]
is this mergeable?

**Comment by KPostOffice** [comment]
@goern yes

**Review by fridex — COMMENTED** [review]
/lgtm

**Review by harshad16 — APPROVED** [review]
/lgtm
thanks :100:

**Pull request merged**
