### PR TITLE
Fixed messages and create initial lock commits

### PR DESCRIPTION
**Pull request by saisankargochhayat**
Fixed gitlab messages.
Fixes the commits access in `_create_initial_lock` method.

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
Should I create another similar function that has looks for the specific sha pip file? Because the one we have in uses master? :)
Yes, using the util function is a really good idea :+1:

**Comment by fridex** [comment]
> Should I create another similar function that has looks for the specific sha pip file? Because the one we have in uses master? :)
> Yes, using the util function is a really good idea

Is it possible to use master also in case of gitlab?

**Comment by saisankargochhayat** [comment]
> > Should I create another similar function that has looks for the specific sha pip file? Because the one we have in uses master? :)
> > Yes, using the util function is a really good idea
> 
> Is it possible to use master also in case of gitlab?

Yes, we can use master or links like this - https://gitlab.com/saisankargochhayat/flake_fork/-/blob/cceda849df1969d2f0fd1cc7336a700093c2ca47/Pipfile
Which would be a good idea?

**Comment by fridex** [comment]
> > > Should I create another similar function that has looks for the specific sha pip file? Because the one we have in uses master? :)
> > > Yes, using the util function is a really good idea
> > 
> > 
> > Is it possible to use master also in case of gitlab?
> 
> Yes, we can use master or links like this - https://gitlab.com/saisankargochhayat/flake_fork/-/blob/cceda849df1969d2f0fd1cc7336a700093c2ca47/Pipfile
> Which would be a good idea?

As kebechet operates on master, putting directly master can work well:

  https://gitlab.com/saisankargochhayat/flake_fork/-/blob/master/Pipfile

It might be also good idea to capture commit sha that caused issues so users know which commits caused issues in already closed issues - as done when the application stack cannot be reproduced.

**Comment by saisankargochhayat** [comment]
So maybe just point to the master pipfile, and also print the commit sha in the message.

**Pull request merged**
