### PR TITLE
Updated glyph to 0.13

### LINKED ISSUE #560: ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Sentry Issue: [KEBECHET-B7](https://sentry.io/organizations/thoth-station/issues/1905991229/?referrer=github_integration)

```
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
  File "kebechet/config.py", line 166, in run_url
    instance.run(**manager_configuration)
  File "kebechet/managers/version/version.py", line 433, in run
    version_file=changelog_file,
  File "kebechet/managers/version/version.py", line 286, in _compute_changelog
    MLModel.by_name(changelog_classifier),
  File "thoth/glyph/lib.py", line 158, in generate_log
    predicted_labels = list(df["labels_predicted"].astype(str)) if df else []
  File "pandas/core/generic.py", line 1327, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "

An error occurred during run of manager {"configuration":{"assignees":["sesheta"],"changelog_file":true,"labels":["bot"],"maintainers":["sesheta","goern","fridex"]}} "<class 'kebechet.managers.version.version.VersionManager'>" for "thoth-station/graph-refresh-job", skipping
```

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies
Fixes #560

### CODE REVIEW

**Review by fridex — APPROVED** [review]
:100:

**Comment by saisankargochhayat** [comment]
@harshad16 might have to manually merge this i guess as pytest would still be failing

**Pull request merged**
