### PR TITLE
add documentation for advise issue

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

New feature for requesting advise through issue creation

### CODE REVIEW

**Review by codificat — CHANGES_REQUESTED** [review]
A couple of minor comments: one sentence does need a fix; the other is a suggested format change (but feel free to ignore it, I'm not convinced either :smiley:)

**Review by harshad16 — COMMENTED** [review]
lgtm
once the suggestion are addressed

**Comment by KPostOffice** [comment]
@codificat PTAL

**Pull request merged**
