### PR TITLE
use upstream solution for adding assignees

### LINKED ISSUE #728: implement upstream in OGR
https://github.com/thoth-station/kebechet/blob/c19384a0f0427d9c54c11b82b4a661074e4e6774/kebechet/managers/manager.py#L163-L168

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in c19384a0f0427d9c54c11b82b4a661074e4e6774 when #725 was merged. cc @KPostOffice.

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies
Fixes #728

Adding assignees is implemented upstream in ogr now

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
nice!
/lgtm

Not sure about ogr version that has the assignee feature present. Should the lock file be updated?

**Comment by KPostOffice** [comment]
@fridex This PR updates the lockfile to the necessary version

**Comment by fridex** [comment]
> @fridex This PR updates the lockfile to the necessary version

I was just not sure as changes in the lock file were done only to environment markers. If that's fine, this can go in 👍🏻 

/lgtm

**Review by fridex — APPROVED** [review]

**Pull request merged**
