### PR TITLE
A big step towards general AI

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
@fridex I think we need replace the string to be replace with - "Hey, Kebechet!\r\n\r\nCreate a new patch release, please."
It doesn't seem to get replaced when we use "\n\n".
Here is the issue I was testing on - [[Link](https://github.com/saisankargochhayat/kebechet_sample/issues/34)]
Working PR on replacing the string with -`'\r\n\r\n'` [[Link](https://github.com/saisankargochhayat/kebechet_sample/pull/41)]

**Comment by fridex** [comment]
> @fridex I think we need replace the string to be replace with - "Hey, Kebechet!\r\n\r\nCreate a new patch release, please."
> It doesn't seem to get replaced when we use "\n\n".
> Here is the issue I was testing on - [[Link](https://github.com/saisankargochhayat/kebechet_sample/issues/34)]
> Working PR on replacing the string with -`'\r\n\r\n'` [[Link](https://github.com/saisankargochhayat/kebechet_sample/pull/41)]

Thanks for testing this out! I tried to addres this in 4f745ebb00a8a699e7878f1e92c3ca2d517f1121

**Comment by saisankargochhayat** [comment]
That's a cool way to handle it :smile: 
LGTM :+1:

**Comment by fridex** [comment]
We should adjust the config to match our knowledge graph (the failure of Thoth's advise):

```
Analysis has encountered errors: Boot pipeline unit SolvedSoftwareEnvironmentBoot failed: "No observations found for 'centos' in version '7' using Python '3.6'".
``` 

merging manually as all the remaining checks are green.

**Pull request merged**
